name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.8

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Terraform plan
        run: terraform plan -input=false
